export const STAGE_WIDTH = 1920;
export const STAGE_HEIGHT = 1080;
export const MENU_WIDTH = 528;
export const PLAY_AREA_X = MENU_WIDTH;
export const PLAY_AREA_WIDTH = STAGE_WIDTH - MENU_WIDTH;
export const PLAY_AREA_HEIGHT = STAGE_HEIGHT;
export const GRID_PADDING = 80;
export const IDLE_MS = 60_000;
export const EDU_OVERLAY_MS = 4500;
